version: '3'
services:
  postgresql:
    image: bitnami/postgresql:15.3.0
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_USERNAME=dbuser
      - POSTGRESQL_DATABASE=keycloakdb
    network_mode: bridge

  keycloak:
    build:
      context: ../../
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_NAME=keycloakdb
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_USER=dbuser
      - KEYCLOAK_DATABASE_PASSWORD=password
    volumes:
        - ../../src/data/import/realm.json:/opt/bitnami/keycloak/data/import/realm.json
        - ../../src/themes/:/opt/bitnami/keycloak/themes
    depends_on:
      - postgresql
    links:
      - postgresql
    ports:
      - "8080:8080"
    network_mode: bridge
